// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/menu.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "go-restaurant-app/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMenuRepository is a mock of MenuRepository interface.
type MockMenuRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMenuRepositoryMockRecorder
}

// MockMenuRepositoryMockRecorder is the mock recorder for MockMenuRepository.
type MockMenuRepositoryMockRecorder struct {
	mock *MockMenuRepository
}

// NewMockMenuRepository creates a new mock instance.
func NewMockMenuRepository(ctrl *gomock.Controller) *MockMenuRepository {
	mock := &MockMenuRepository{ctrl: ctrl}
	mock.recorder = &MockMenuRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMenuRepository) EXPECT() *MockMenuRepositoryMockRecorder {
	return m.recorder
}

// GetMenuByOrderCode mocks base method.
func (m *MockMenuRepository) GetMenuByOrderCode(ctx context.Context, orderCode string) (model.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenuByOrderCode", ctx, orderCode)
	ret0, _ := ret[0].(model.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenuByOrderCode indicates an expected call of GetMenuByOrderCode.
func (mr *MockMenuRepositoryMockRecorder) GetMenuByOrderCode(ctx, orderCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenuByOrderCode", reflect.TypeOf((*MockMenuRepository)(nil).GetMenuByOrderCode), ctx, orderCode)
}

// GetMenuByType mocks base method.
func (m *MockMenuRepository) GetMenuByType(ctx context.Context, menuType string) ([]model.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenuByType", ctx, menuType)
	ret0, _ := ret[0].([]model.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenuByType indicates an expected call of GetMenuByType.
func (mr *MockMenuRepositoryMockRecorder) GetMenuByType(ctx, menuType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenuByType", reflect.TypeOf((*MockMenuRepository)(nil).GetMenuByType), ctx, menuType)
}
